services:
  kuloffice:
    image: kulofficelocal
    container_name: kuloffice
    ports:
      # Map the HTTP port defined in .env to container port 8080.
      - "${KULOFFICE_SERVER_HTTP_PORT}:${KULOFFICE_SERVER_HTTP_PORT}"
    environment:
      # Server Ports
      - KULOFFICE_SERVER_GRPC_PORT=${KULOFFICE_SERVER_GRPC_PORT}
      - KULOFFICE_SERVER_HTTP_PORT=${KULOFFICE_SERVER_HTTP_PORT}

      # Server Config
      - KULOFFICE_SERVER_GRPC_MAX_RECV_MSG_SIZE=${KULOFFICE_SERVER_GRPC_MAX_RECV_MSG_SIZE}
      - KULOFFICE_SERVER_GRPC_MAX_SEND_MSG_SIZE=${KULOFFICE_SERVER_GRPC_MAX_SEND_MSG_SIZE}

      # Database
      - KULOFFICE_DATABASE_URL=${KULOFFICE_DATABASE_URL}

      # CORS
      - KULOFFICE_SERVER_HTTP_CORS_ALLOWED_ORIGINS=${KULOFFICE_SERVER_HTTP_CORS_ALLOWED_ORIGINS}
      - KULOFFICE_SERVER_HTTP_CORS_ALLOWED_METHODS=${KULOFFICE_SERVER_HTTP_CORS_ALLOWED_METHODS}
      - KULOFFICE_SERVER_HTTP_CORS_ALLOWED_HEADERS=${KULOFFICE_SERVER_HTTP_CORS_ALLOWED_HEADERS}

      #SMS 
      - KULOFFICE_SMS_BASE_URL=${KULOFFICE_SMS_BASE_URL}
      - KULOFFICE_SMS_API_KEY=${KULOFFICE_SMS_API_KEY}
      - KULOFFICE_SMS_PROVIDER_ID=${KULOFFICE_SMS_PROVIDER_ID}
      - KULOFFICE_SMS_LIVE=${KULOFFICE_SMS_LIVE}

      #Adapter
      - KULOFFICE_ADAPTER_BLNK_BASE_URL=${KULOFFICE_ADAPTER_BLNK_BASE_URL}
      - KULOFFICE_ADAPTER_BLNK_LEDGER_PAYOUT=${KULOFFICE_ADAPTER_BLNK_LEDGER_PAYOUT}
      - KULOFFICE_ADAPTER_BLNK_LEDGER_PAYIN=${KULOFFICE_ADAPTER_BLNK_LEDGER_PAYIN}
      - KULOFFICE_ADAPTER_BLNK_LEDGER_PNLO=${KULOFFICE_ADAPTER_BLNK_LEDGER_PNLO}
      - KULOFFICE_ADAPTER_BLNK_LEDGER_PNLI=${KULOFFICE_ADAPTER_BLNK_LEDGER_PNLI}
      - KULOFFICE_ADAPTER_BLNK_LEDGER_CUSTOMER_ACCOUNTS=${KULOFFICE_ADAPTER_BLNK_LEDGER_CUSTOMER_ACCOUNTS}
      - KULOFFICE_ADAPTER_BLNK_LEDGER_DEPOSIT=${KULOFFICE_ADAPTER_BLNK_LEDGER_DEPOSIT}
      - KULOFFICE_ADAPTER_BLNK_BALANCE_DEPOSIT=${KULOFFICE_ADAPTER_BLNK_BALANCE_DEPOSIT}

      #Engine
      - KULOFFICE_ENGINE_RETRIES=${KULOFFICE_ENGINE_RETRIES}

      #MiniAiLive
      - KULOFFICE_MINIAILIVE_FACE_LIVESS_URL=${KULOFFICE_MINIAILIVE_FACE_LIVENESS_URL}
      - KULOFFICE_MINIAILIVE_FACE_MATCH_URL=${KULOFFICE_MINIAILIVE_FACE_MATCH_URL}
      - KULOFFICE_MINIAILIVE_DOCUMENT_LIVENESS_URL=${KULOFFICE_MINIAILIVE_DOCUMENT_LIVENESS_URL}
      - KULOFFICE_MINIAILIVE_DOCUMENT_EXTRACTION_URL=${KULOFFICE_MINIAILIVE_DOCUMENT_EXTRACTION_URL}
      - KULOFFICE_MINIAILIVE_LIVENESS_PROBABILITY_THRESHOLD=${KULOFFICE_MINIAILIVE_LIVENESS_PROBABILITY_THRESHOLD}
      # License

      - KULOFFICE_LICENSE_KEY=${KULOFFICE_LICENSE_KEY}

      #NUIB API
      - KULOFFICE_NUIBAPI_REQ_SINGULAR_URL=${KULOFFICE_NUIBAPI_REQ_SINGULAR_URL}
      - KULOFFICE_NUIBAPI_REQ_COLECTIVO_URL=${KULOFFICE_NUIBAPI_REQ_COLECTIVO_URL}
      - KULOFFICE_NUIBAPI_RESPONSE_URL=${KULOFFICE_NUIBAPI_RESPONSE_URL}
      - KULOFFICE_NUIBAPI_API_KEY=${KULOFFICE_NUIBAPI_API_KEY}

      #SMS Templates
      - KULOFFICE_ENGINE_MESSAGE_TRANSFER=${KULOFFICE_ENGINE_MESSAGE_TRANSFER}
      - KULOFFICE_ENGINE_MESSAGE_DEPOSIT=${KULOFFICE_ENGINE_MESSAGE_DEPOSIT}
      - KULOFFICE_ENGINE_MESSAGE_RECEIVE=${KULOFFICE_ENGINE_MESSAGE_RECEIVE}
    restart: unless-stopped
    depends_on:
      kuloffice-db:
        condition: service_started
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:${KULOFFICE_SERVER_HTTP_PORT}/v1/system/status || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5

  # kuloffice-bootstrap:
  #   image: ${KULOFFICE_BOOTSTRAP_IMAGE:-pavulla/kuloffice-bootstrap:latest}
  #   container_name: kuloffice-bootstrap
  #   environment:
  #     # Bootstrap
  #     - KULOFFICE_BOOTSTRAP_API_BASE_URL=${KULOFFICE_BOOTSTRAP_API_BASE_URL}
  #     - KULOFFICE_BOOTSTRAP_SYSTEM_USER=${KULOFFICE_BOOTSTRAP_SYSTEM_USER}
  #     - KULOFFICE_BOOTSTRAP_SYSTEM_USER_USERNAME=${KULOFFICE_BOOTSTRAP_SYSTEM_USER_USERNAME}
  #     - KULOFFICE_BOOTSTRAP_SYSTEM_USER_PASSWORD=${KULOFFICE_BOOTSTRAP_SYSTEM_USER_PASSWORD}
  #     - KULOFFICE_BOOTSTRAP_SYSTEM_USER_EMAIL=${KULOFFICE_BOOTSTRAP_SYSTEM_USER_EMAIL}
  #     - KULOFFICE_BOOTSTRAP_SYSTEM_USER_FIRST_NAME=${KULOFFICE_BOOTSTRAP_SYSTEM_USER_FIRST_NAME}
  #     - KULOFFICE_BOOTSTRAP_SYSTEM_USER_LAST_NAME=${KULOFFICE_BOOTSTRAP_SYSTEM_USER_LAST_NAME}
  #     - KULOFFICE_BOOTSTRAP_IDP=${KULOFFICE_BOOTSTRAP_IDP}
  #     - KULOFFICE_BOOTSTRAP_IDP_NAME=${KULOFFICE_BOOTSTRAP_IDP_NAME}
  #     - KULOFFICE_BOOTSTRAP_IDP_TYPE=${KULOFFICE_BOOTSTRAP_IDP_TYPE}
  #     - KULOFFICE_BOOTSTRAP_IDP_DISCOVERY_URL=${KULOFFICE_BOOTSTRAP_IDP_DISCOVERY_URL}
  #     - KULOFFICE_BOOTSTRAP_IDP_CLIENT_ID=${KULOFFICE_BOOTSTRAP_IDP_CLIENT_ID}
  #     - KULOFFICE_BOOTSTRAP_IDP_CLIENT_SECRET=${KULOFFICE_BOOTSTRAP_IDP_CLIENT_SECRET}
  #     - KULOFFICE_BOOTSTRAP_IDP_ISSUER_URL=${KULOFFICE_BOOTSTRAP_IDP_ISSUER_URL}
  #   restart: unless-stopped
  #   # Use entrypoint to ensure proper command execution
  #   entrypoint: /bin/sh
  #   command: -c "sleep 30 && /opt/kuloffice/bin/kuloffice-bootstrap"

  kuloffice-db:
    image: postgres:17
    container_name: kuloffice-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-kuloffice}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-kuloffice}
      - POSTGRES_DB=${POSTGRES_DB:-kuloffice}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-kuloffice} -d ${POSTGRES_DB:-kuloffice}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # kuloffice-proxy:
  #   image: nginx:alpine
  #   container_name: kuloffice-proxy
  #   ports:
  #     - "18080:80"
  #     - "18443:443"
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  #   restart: unless-stopped

volumes:
  pgdata:
